// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func BottomNav() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bottom-nav\"><a href=\"/home\" class=\"bottom-nav-item\"><i class=\"material-icons\">home</i> <span>Home</span></a> <a href=\"/search\" class=\"bottom-nav-item\"><i class=\"material-icons\">search</i> <span>Search</span></a> <a href=\"/add\" class=\"bottom-nav-item\"><i class=\"material-icons\">add</i> <span>Add</span></a> <a href=\"/notifications\" class=\"bottom-nav-item\"><i class=\"material-icons\">notifications</i> <span>Notifications</span></a> <a href=\"/profile\" class=\"bottom-nav-item\"><i class=\"material-icons\">person</i> <span>Profile</span></a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
